#!/bin/bash
set -e

#sozo --offline build
sozo migrate --rpc-url https://api.cartridge.gg/x/underdark/katana --account-address 0x4e9c35bb113eaf274457edb2473437b02fe636f14c477aa110ba8d3626d3282 --verbose

scripts/default_auth.sh

# cp target/dev/manifest.json ../client/src/

# cd ../client
# npm run codegen
# npm run create-components

echo "--- DONE!"
