#!/bin/bash
set -e

#sozo --offline build
sozo migrate --rpc-url https://api.cartridge.gg/x/underdark/katana

scripts/default_auth.sh

cp target/dev/manifest.json ../client/src/

cd ../client
yarn run codegen
yarn run create-components

echo "--- DONE!"
