#!/bin/bash
set -e

export WORLD_ADDRESS="0x7006ea4fd2de52944def100605e48ba82b8c4d15a6bd5ef04fbc579d8b00076"
export RPC_URL="http://localhost:5050/"


#sozo --offline build
sozo migrate

scripts/default_auth.sh

cp target/dev/manifest.json ../client/src/

cd ../client
npm run codegen
npm run create-components $RPC_URL $WORLD_ADDRESS

echo "--- DONE!"
